CREATE TABLE cash_sessions (
    cash_session_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buyin MONEY NOT NULL,
    cashout MONEY NOT NULL,
    hours_played FLOAT(2) NOT NULL,
    date TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id INTEGER,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

